name: Build and Deploy Jekyll to GitHub Pages

on:
  push:
    branches: [ main ]        # ← change if your default branch differs
  workflow_dispatch:

# REQUIRED for Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Prevent overlapping deploys
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'         # or your version
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll
        run: JEKYLL_ENV=production bundle exec jekyll build --trace
        # If you're publishing a prebuilt site (no Jekyll on Pages), keep .nojekyll INSIDE _site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site                 # ← must point to your built output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages             # ← required
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4  # ← upgrade to v4